// ============================================================
// GRIVA — Complete Roadmap Definitions (52 roadmaps)
// Used by: /api/seed-roadmaps  +  topic detail pages
// ============================================================

export interface RoadmapDef {
    title: string;
    description: string;
    category: string;
    sections: { title: string; topics: string[] }[];
}

export const ROADMAPS: RoadmapDef[] = [
    // ── 1 ── Web Development ───────────────────────────────────────────────
    {
        title: "Frontend Developer",
        description: "Step by step guide to becoming a modern frontend developer in 2026.",
        category: "Web Development",
        sections: [
            { title: "Internet Basics", topics: ["How does the Internet work?", "What is HTTP?", "DNS and how it works", "What is a Domain Name?", "Browsers and how they work", "What is Hosting?"] },
            { title: "HTML", topics: ["Learn the basics", "Semantic HTML", "Forms and Validations", "Accessibility", "SEO Basics"] },
            { title: "CSS", topics: ["Learn the basics", "Making Layouts (Flexbox, Grid)", "Responsive Design", "CSS Architecture (BEM)", "CSS Preprocessors (Sass)", "Tailwind CSS", "CSS Animations"] },
            { title: "JavaScript", topics: ["Syntax and Basics", "DOM Manipulation", "Fetch API / Ajax", "ES6+ Features", "Closures & Scope", "Promises & Async/Await", "Event Loop", "Modules"] },
            { title: "Version Control", topics: ["Git basics", "GitHub", "Branching strategies"] },
            { title: "Package Managers", topics: ["npm", "yarn", "pnpm"] },
            { title: "Frameworks", topics: ["React", "Vue.js", "Angular", "Svelte", "Next.js", "Nuxt.js"] },
            { title: "TypeScript", topics: ["Types and Interfaces", "Generics", "Type Guards", "Utility Types", "Decorators"] },
            { title: "Testing", topics: ["Unit Testing (Jest, Vitest)", "Integration Testing", "E2E Testing (Cypress, Playwright)"] },
            { title: "Performance", topics: ["Core Web Vitals", "Lazy Loading", "Code Splitting", "Image Optimization", "Caching Strategies"] },
        ],
    },
    {
        title: "Backend Developer",
        description: "Step by step guide to becoming a modern backend developer in 2026.",
        category: "Web Development",
        sections: [
            { title: "Internet & OS", topics: ["How does the Internet work?", "OS and General Knowledge", "Process Management", "Threads and Concurrency", "Memory Management", "Terminal Usage"] },
            { title: "Programming Language", topics: ["JavaScript / Node.js", "Python", "Go", "Rust", "Java", "C#"] },
            { title: "Databases", topics: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "SQLite", "ORM (Prisma, Drizzle)"] },
            { title: "APIs", topics: ["REST", "GraphQL", "gRPC", "WebSockets", "Authentication (JWT, OAuth)", "API Security"] },
            { title: "Caching", topics: ["CDN", "Server-side caching", "Redis caching", "Client-side caching"] },
            { title: "Testing", topics: ["Unit Testing", "Integration Testing", "Functional Testing"] },
            { title: "CI/CD", topics: ["GitHub Actions", "Jenkins", "Docker", "Kubernetes"] },
            { title: "Architecture", topics: ["Monolithic vs Microservices", "Serverless", "SOA", "Message Brokers (RabbitMQ, Kafka)"] },
            { title: "Scaling", topics: ["Horizontal vs Vertical Scaling", "Load Balancing", "Database Sharding", "Rate Limiting"] },
        ],
    },
    {
        title: "DevOps Engineer",
        description: "Step by step guide to becoming a DevOps engineer with hands-on tools.",
        category: "Infrastructure",
        sections: [
            { title: "OS Concepts", topics: ["Process Management", "Networking basics", "Sockets", "POSIX", "File Systems", "Startup Management (systemd)"] },
            { title: "Networking", topics: ["DNS", "HTTP/HTTPS", "FTP/SFTP", "SSL/TLS", "SSH", "Load Balancers", "Reverse Proxy"] },
            { title: "Servers", topics: ["Linux (Ubuntu, CentOS)", "Nginx", "Apache", "Caddy"] },
            { title: "Containers", topics: ["Docker", "Docker Compose", "Podman", "LXC"] },
            { title: "Orchestration", topics: ["Kubernetes", "Docker Swarm", "Nomad", "Helm Charts"] },
            { title: "CI/CD", topics: ["GitHub Actions", "GitLab CI", "Jenkins", "CircleCI", "ArgoCD"] },
            { title: "Infrastructure as Code", topics: ["Terraform", "Ansible", "Pulumi", "CloudFormation"] },
            { title: "Monitoring", topics: ["Prometheus", "Grafana", "Datadog", "ELK Stack", "Jaeger"] },
            { title: "Cloud Providers", topics: ["AWS", "Google Cloud", "Azure", "DigitalOcean"] },
        ],
    },
    {
        title: "Full Stack Developer",
        description: "Complete guide to becoming a full stack web developer.",
        category: "Web Development",
        sections: [
            { title: "Frontend Fundamentals", topics: ["HTML & Semantic Markup", "CSS & Responsive Design", "JavaScript ES6+", "TypeScript"] },
            { title: "Frontend Frameworks", topics: ["React.js", "Next.js", "Vue.js", "Svelte"] },
            { title: "Backend Fundamentals", topics: ["Node.js & Express", "Python & Django/FastAPI", "REST API Design", "GraphQL"] },
            { title: "Databases", topics: ["PostgreSQL", "MongoDB", "Redis", "Supabase", "Prisma ORM"] },
            { title: "Authentication", topics: ["JWT Tokens", "OAuth 2.0", "Session Management", "Role-Based Access"] },
            { title: "DevOps Basics", topics: ["Docker", "CI/CD Pipelines", "Cloud Deployment (Vercel, AWS)", "Environment Variables", "Monitoring & Logging"] },
            { title: "Testing", topics: ["Unit Tests", "Integration Tests", "E2E Tests", "API Testing"] },
        ],
    },
    {
        title: "AI & Data Science",
        description: "Guide to becoming an AI engineer and data scientist.",
        category: "AI & ML",
        sections: [
            { title: "Mathematics", topics: ["Linear Algebra", "Calculus", "Probability & Statistics", "Optimization"] },
            { title: "Python for Data Science", topics: ["NumPy", "Pandas", "Matplotlib / Seaborn", "Jupyter Notebooks", "Scikit-learn"] },
            { title: "Machine Learning", topics: ["Supervised Learning", "Unsupervised Learning", "Feature Engineering", "Model Evaluation", "Cross Validation", "Ensemble Methods"] },
            { title: "Deep Learning", topics: ["Neural Networks", "CNNs", "RNNs / LSTMs", "Transformers", "GANs", "PyTorch", "TensorFlow"] },
            { title: "NLP", topics: ["Text Preprocessing", "Word Embeddings", "Attention Mechanism", "BERT / GPT", "Hugging Face Transformers", "LLM Fine-tuning"] },
            { title: "Computer Vision", topics: ["Image Classification", "Object Detection (YOLO)", "Image Segmentation", "Stable Diffusion", "OpenCV"] },
            { title: "MLOps", topics: ["Model Deployment", "MLflow", "DVC", "Model Monitoring", "A/B Testing"] },
        ],
    },
    {
        title: "Cybersecurity",
        description: "Guide to becoming a cybersecurity expert.",
        category: "Security",
        sections: [
            { title: "Networking", topics: ["TCP/IP Model", "OSI Model", "Firewalls", "VPNs", "Subnetting", "Wireshark"] },
            { title: "Operating Systems", topics: ["Linux Administration", "Windows Security", "File Permissions", "Process Monitoring"] },
            { title: "Web Security", topics: ["OWASP Top 10", "SQL Injection", "XSS", "CSRF", "Security Headers", "Content Security Policy"] },
            { title: "Cryptography", topics: ["Symmetric Encryption (AES)", "Asymmetric Encryption (RSA)", "Hashing (SHA, bcrypt)", "Digital Signatures", "TLS/SSL"] },
            { title: "Penetration Testing", topics: ["Nmap", "Burp Suite", "Metasploit", "Kali Linux", "Social Engineering"] },
            { title: "Incident Response", topics: ["Threat Detection", "SIEM", "Forensics", "Malware Analysis", "Vulnerability Management"] },
        ],
    },
    {
        title: "React Developer",
        description: "Everything you need to become a proficient React developer.",
        category: "Web Development",
        sections: [
            { title: "React Fundamentals", topics: ["JSX", "Components", "Props", "State", "Event Handling", "Conditional Rendering", "Lists and Keys"] },
            { title: "Hooks", topics: ["useState", "useEffect", "useContext", "useReducer", "useRef", "useMemo", "useCallback", "Custom Hooks"] },
            { title: "State Management", topics: ["Context API", "Redux Toolkit", "Zustand", "Jotai", "Recoil"] },
            { title: "Routing", topics: ["React Router", "Next.js App Router", "Dynamic Routes", "Protected Routes"] },
            { title: "Styling", topics: ["CSS Modules", "Styled Components", "Tailwind CSS", "Framer Motion"] },
            { title: "API Integration", topics: ["Fetch / Axios", "React Query (TanStack Query)", "SWR", "GraphQL with Apollo"] },
            { title: "Testing", topics: ["React Testing Library", "Jest", "Cypress", "Playwright"] },
            { title: "Performance", topics: ["React.memo", "Code Splitting", "Lazy Loading", "Suspense", "React Server Components"] },
        ],
    },
    {
        title: "Python Developer",
        description: "Complete guide to becoming a Python developer.",
        category: "Programming",
        sections: [
            { title: "Basics", topics: ["Syntax and Variables", "Data Types", "Control Flow", "Functions", "Modules", "List Comprehensions", "Error Handling"] },
            { title: "OOP", topics: ["Classes and Objects", "Inheritance", "Polymorphism", "Encapsulation", "Decorators", "Magic Methods"] },
            { title: "Advanced Python", topics: ["Generators", "Iterators", "Context Managers", "Multithreading", "Multiprocessing", "Asyncio"] },
            { title: "Web Frameworks", topics: ["Django", "Flask", "FastAPI", "Uvicorn", "Django REST Framework"] },
            { title: "Data & ML", topics: ["NumPy", "Pandas", "Matplotlib", "Scikit-learn", "TensorFlow", "PyTorch"] },
            { title: "DevOps & Tools", topics: ["Virtual Environments (venv)", "Poetry", "Docker", "Testing (pytest)", "Type Hints", "Linting (Ruff, Black)"] },
        ],
    },
    {
        title: "Android Developer",
        description: "Guide to becoming a modern Android developer with Kotlin.",
        category: "Mobile",
        sections: [
            { title: "Kotlin Basics", topics: ["Syntax & Variables", "Control Flow", "Functions", "OOP in Kotlin", "Null Safety", "Coroutines"] },
            { title: "Android Fundamentals", topics: ["Activities & Fragments", "Layouts & Views", "Intents", "Permissions", "Lifecycle"] },
            { title: "Jetpack Compose", topics: ["Composable Functions", "State Management", "Navigation", "Theming", "Animations", "LazyColumn & LazyRow"] },
            { title: "Architecture", topics: ["MVVM Pattern", "Repository Pattern", "Room Database", "Dependency Injection (Hilt)", "WorkManager"] },
            { title: "Networking", topics: ["Retrofit", "OkHttp", "Kotlin Serialization", "WebSockets"] },
            { title: "Testing & Release", topics: ["Unit Testing", "UI Testing (Espresso)", "App Signing", "Play Store Publishing"] },
        ],
    },
    {
        title: "iOS Developer",
        description: "Complete guide to iOS development with Swift and SwiftUI.",
        category: "Mobile",
        sections: [
            { title: "Swift Basics", topics: ["Variables & Constants", "Optionals", "Closures", "Protocols", "Generics", "Error Handling", "Concurrency (async/await)"] },
            { title: "SwiftUI", topics: ["Views & Modifiers", "State & Binding", "NavigationStack", "Lists & Grids", "Animations", "Custom Components"] },
            { title: "UIKit", topics: ["UIViewController", "UITableView", "Auto Layout", "Storyboards vs Programmatic"] },
            { title: "Data & Storage", topics: ["Core Data", "SwiftData", "UserDefaults", "Keychain", "CloudKit"] },
            { title: "Networking", topics: ["URLSession", "Codable", "REST APIs", "WebSockets"] },
            { title: "App Store", topics: ["App Signing", "TestFlight", "App Store Connect", "In-App Purchases", "Push Notifications"] },
        ],
    },
    {
        title: "Blockchain Developer",
        description: "Guide to becoming a blockchain and Web3 developer.",
        category: "Web3",
        sections: [
            { title: "Blockchain Basics", topics: ["What is Blockchain?", "Decentralization", "Consensus Mechanisms", "Cryptographic Hashing", "Wallets & Keys"] },
            { title: "Ethereum", topics: ["EVM", "Gas & Transactions", "Smart Contracts", "Solidity Language", "Hardhat", "Foundry"] },
            { title: "Smart Contracts", topics: ["Solidity Syntax", "ERC-20 Tokens", "ERC-721 NFTs", "OpenZeppelin", "Upgradeable Contracts", "Security Auditing"] },
            { title: "DApps", topics: ["Web3.js / Ethers.js", "Wagmi + Viem", "MetaMask Integration", "IPFS", "The Graph"] },
            { title: "DeFi", topics: ["AMMs", "Lending Protocols", "Yield Farming", "Stablecoins", "Flash Loans"] },
            { title: "Layer 2 & Scaling", topics: ["Rollups (Optimistic, ZK)", "Polygon", "Arbitrum", "Base", "State Channels"] },
        ],
    },
    {
        title: "System Design",
        description: "Learn how to design scalable, distributed systems.",
        category: "Architecture",
        sections: [
            { title: "Fundamentals", topics: ["Client-Server Model", "IP, DNS, HTTP", "Scaling (Vertical vs Horizontal)", "CAP Theorem", "Latency vs Throughput"] },
            { title: "Databases", topics: ["SQL vs NoSQL", "ACID Properties", "Database Indexing", "Sharding", "Replication", "Partitioning"] },
            { title: "Caching", topics: ["Cache Strategies", "Redis", "Memcached", "CDN", "Cache Invalidation"] },
            { title: "Messaging", topics: ["Message Queues", "Kafka", "RabbitMQ", "Pub/Sub Pattern", "Event-Driven Architecture"] },
            { title: "Design Patterns", topics: ["URL Shortener", "Rate Limiter", "Chat System", "Search Engine", "Social Media Feed", "Video Streaming"] },
            { title: "Infrastructure", topics: ["Load Balancers", "Reverse Proxy", "API Gateway", "Microservices", "Service Mesh", "Observability"] },
        ],
    },

    // ── 2 ── New Web Development Roadmaps ─────────────────────────────────
    {
        title: "Vue.js Developer",
        description: "Comprehensive guide to building modern web apps with Vue 3.",
        category: "Web Development",
        sections: [
            { title: "Vue 3 Basics", topics: ["Vue Instance & App", "Template Syntax", "Data Binding (v-bind)", "Event Handling (v-on)", "Conditional Rendering (v-if, v-show)", "List Rendering (v-for)"] },
            { title: "Components", topics: ["Component Basics", "Props & Emits", "Slots", "Component Lifecycle", "Dynamic Components", "Async Components"] },
            { title: "Composition API", topics: ["setup()", "ref & reactive", "computed & watch", "Lifecycle Hooks in Composition API", "Composables", "provide / inject"] },
            { title: "State Management", topics: ["Pinia Basics", "Stores & Actions", "Getters", "State Persistence", "Vuex (legacy)"] },
            { title: "Vue Router", topics: ["Router Setup", "Dynamic Routes", "Nested Routes", "Navigation Guards", "Lazy Loading Routes"] },
            { title: "Nuxt.js", topics: ["File-based Routing", "Server-Side Rendering", "Data Fetching (useFetch)", "Nuxt Modules", "Deployment"] },
            { title: "Testing & Performance", topics: ["Vitest", "Vue Test Utils", "Component Testing", "Lazy Loading", "Tree Shaking"] },
        ],
    },
    {
        title: "Angular Developer",
        description: "Complete roadmap to mastering Angular for enterprise applications.",
        category: "Web Development",
        sections: [
            { title: "TypeScript for Angular", topics: ["Type Annotations", "Interfaces & Classes", "Decorators", "Generics", "Strict Mode"] },
            { title: "Angular Core", topics: ["Modules (NgModule)", "Components", "Templates", "Data Binding", "Directives", "Pipes"] },
            { title: "Services & DI", topics: ["Dependency Injection", "Services", "Providers", "Hierarchical Injectors"] },
            { title: "Forms", topics: ["Template-Driven Forms", "Reactive Forms", "Form Validation", "Custom Validators"] },
            { title: "RxJS & Observables", topics: ["Observables & Subscriptions", "Operators (map, filter, switchMap)", "Subject & BehaviorSubject", "Async Pipe"] },
            { title: "Routing", topics: ["RouterModule Setup", "Route Guards (CanActivate)", "Lazy Loading", "Resolver"] },
            { title: "Testing", topics: ["TestBed", "ComponentFixture", "Mocking Services", "E2E with Cypress"] },
            { title: "Angular Material", topics: ["Component Library Setup", "Theming", "CDK", "Accessibility"] },
        ],
    },
    {
        title: "Node.js Developer",
        description: "Master Node.js for building scalable server-side applications.",
        category: "Web Development",
        sections: [
            { title: "Node.js Fundamentals", topics: ["Node Architecture & Event Loop", "Modules (CommonJS, ESM)", "File System (fs)", "Streams & Buffers", "Child Processes", "npm & package.json"] },
            { title: "Async Programming", topics: ["Callbacks", "Promises", "Async/Await", "EventEmitter", "Error Handling"] },
            { title: "Express.js", topics: ["Routing", "Middleware", "Error Handling Middleware", "Template Engines", "Static Files"] },
            { title: "REST API Design", topics: ["CRUD Endpoints", "Request Validation", "Pagination", "Filtering & Sorting", "Rate Limiting", "Versioning"] },
            { title: "Database Integration", topics: ["PostgreSQL with pg", "MongoDB with Mongoose", "Redis Caching", "Prisma ORM", "Connection Pooling"] },
            { title: "Authentication & Security", topics: ["JWT Authentication", "Passport.js", "Helmet.js", "CORS", "Input Sanitization"] },
            { title: "Testing", topics: ["Jest", "Supertest", "Mocking", "Integration Tests"] },
            { title: "Deployment", topics: ["PM2 Process Manager", "Docker Containers", "Heroku / Railway", "AWS EC2 / Lambda", "Environment Variables"] },
        ],
    },
    {
        title: "Next.js Developer",
        description: "Build production-grade web apps with Next.js App Router.",
        category: "Web Development",
        sections: [
            { title: "React Prerequisites", topics: ["React Server Components", "Hooks Fundamentals", "Suspense & Error Boundaries", "Context API"] },
            { title: "Next.js Core", topics: ["App Router vs Pages Router", "File-based Routing", "Layouts & Templates", "Loading & Error States", "Metadata API"] },
            { title: "Data Fetching", topics: ["Server Components (async/await)", "fetch with caching", "revalidatePath / revalidateTag", "Streaming with Suspense", "Client-side fetching (SWR)"] },
            { title: "API Routes", topics: ["Route Handlers", "Dynamic API Routes", "Middleware", "Edge Runtime", "Webhooks"] },
            { title: "Authentication", topics: ["Auth.js (next-auth)", "JWT Strategy", "Session Management", "OAuth Providers", "Protected Routes with Middleware"] },
            { title: "Styling & UI", topics: ["Tailwind CSS", "shadcn/ui", "CSS Modules", "Framer Motion", "Dark Mode"] },
            { title: "Performance", topics: ["Image Optimization (next/image)", "Font Optimization", "Code Splitting", "ISR", "Partial Prerendering"] },
            { title: "Deployment", topics: ["Vercel Deployment", "Environment Variables", "Edge Config", "Analytics", "Caching Strategies"] },
        ],
    },
    {
        title: "Svelte Developer",
        description: "Learn Svelte and SvelteKit for high-performance web apps.",
        category: "Web Development",
        sections: [
            { title: "Svelte Basics", topics: ["Component Syntax", "Reactivity ($:", "Props", "Events", "Lifecycle Hooks", "Slots"] },
            { title: "Svelte Reactivity", topics: ["Reactive Declarations", "Reactive Statements", "Stores (writable, readable, derived)", "Context API"] },
            { title: "SvelteKit", topics: ["File-based Routing", "Load Functions", "Form Actions", "Hooks (handle)", "Error Pages", "Adapters"] },
            { title: "Styling & Animations", topics: ["Scoped CSS", "CSS Variables", "Built-in Transitions", "Custom Animations", "Motion"] },
            { title: "Advanced Svelte", topics: ["Special Elements", "Bind Directives", "Actions", "Content Projection", "Svelte 5 Runes"] },
            { title: "Testing & Deployment", topics: ["Vitest", "Playwright", "Adapter-vercel", "Adapter-node", "Performance Optimization"] },
        ],
    },
    {
        title: "GraphQL Developer",
        description: "Master GraphQL for flexible and efficient API development.",
        category: "Web Development",
        sections: [
            { title: "GraphQL Basics", topics: ["What is GraphQL?", "Schema Definition Language (SDL)", "Queries", "Mutations", "Subscriptions", "Introspection"] },
            { title: "Schema Design", topics: ["Types (Scalar, Object, Enum, Union, Interface)", "Connections & Pagination", "Input Types", "Custom Scalars", "Directives"] },
            { title: "Resolvers", topics: ["Resolver Functions", "Resolver Chain", "DataLoader (N+1 Problem)", "Context & Info", "Error Handling"] },
            { title: "Apollo Server", topics: ["Server Setup", "Plugins", "Caching", "Federated Schemas", "Subscriptions (WebSockets)"] },
            { title: "Apollo Client", topics: ["Client Setup", "useQuery & useMutation", "Local State", "Optimistic UI", "Cache Normalization"] },
            { title: "Security & Performance", topics: ["Authentication in Context", "Authorization (Field-level)", "Depth Limiting", "Query Complexity", "Persisted Queries"] },
        ],
    },
    {
        title: "Django Developer",
        description: "Build robust web applications with Django and Django REST Framework.",
        category: "Web Development",
        sections: [
            { title: "Django Fundamentals", topics: ["MVT Architecture", "URL Routing", "Views (FBV & CBV)", "Templates", "Static Files", "Settings"] },
            { title: "Models & ORM", topics: ["Model Definition", "Field Types", "Migrations", "QuerySets", "Aggregation", "Managers", "Signals"] },
            { title: "Admin & Forms", topics: ["Admin Customization", "Form Classes", "ModelForms", "Form Validation", "File Uploads"] },
            { title: "Authentication", topics: ["Built-in Auth System", "Custom User Model", "Permissions & Groups", "Login/Logout/Register", "Password Reset"] },
            { title: "Django REST Framework", topics: ["Serializers", "APIView & ViewSets", "Routers", "Authentication (Token, JWT)", "Throttling & Filtering", "Pagination"] },
            { title: "Celery & Async", topics: ["Celery Setup", "Tasks & Beat Scheduler", "Redis as Broker", "Monitoring (Flower)"] },
            { title: "Deployment", topics: ["Gunicorn + Nginx", "Docker", "PostgreSQL on Production", "Static Files (WhiteNoise, S3)", "Heroku / Railway / Render"] },
        ],
    },
    {
        title: "FastAPI Developer",
        description: "Build high-performance async APIs with FastAPI and Python.",
        category: "Web Development",
        sections: [
            { title: "Python Async Basics", topics: ["Async/Await", "Coroutines", "Event Loop", "asyncio Library", "Concurrent Tasks"] },
            { title: "FastAPI Core", topics: ["App Setup", "Path & Query Parameters", "Request Body", "Response Models", "Status Codes", "Headers & Cookies"] },
            { title: "Pydantic", topics: ["BaseModel", "Field Validation", "Nested Models", "Custom Validators", "Settings Management (pydantic-settings)"] },
            { title: "Database Integration", topics: ["SQLAlchemy Core & ORM", "Async SQLAlchemy", "Alembic Migrations", "SQLModel", "MongoDB with Motor"] },
            { title: "Authentication & Security", topics: ["OAuth2 with Password Flow", "JWT Tokens", "Scopes & Permissions", "API Key Auth", "CORS Middleware"] },
            { title: "Background Tasks & WebSockets", topics: ["Background Tasks", "Celery Integration", "WebSocket Endpoints", "Server-Sent Events"] },
            { title: "Testing & Deployment", topics: ["TestClient", "pytest-asyncio", "Docker", "Uvicorn in Production", "Kubernetes", "Auto-generated Docs (Swagger)"] },
        ],
    },
    {
        title: "Spring Boot Developer",
        description: "Master Java backend development with Spring Boot.",
        category: "Web Development",
        sections: [
            { title: "Java Fundamentals", topics: ["OOP Concepts", "Generics & Collections", "Streams & Lambdas", "Optional", "Records & Sealed Classes", "Exception Handling"] },
            { title: "Spring Core", topics: ["IoC Container", "Dependency Injection", "Bean Lifecycle", "Application Context", "Spring Profiles"] },
            { title: "Spring Boot", topics: ["Auto-configuration", "Starters", "application.yml", "Actuator", "DevTools", "CommandLineRunner"] },
            { title: "REST APIs", topics: ["RestController", "Request Mapping", "DTOs & Validation (javax)", "Exception Handlers", "HATEOAS", "OpenAPI / Swagger"] },
            { title: "Spring Data JPA", topics: ["Entity & Repository", "JPQL Queries", "Pagination & Sorting", "Transactions", "Projections", "Flyway Migrations"] },
            { title: "Spring Security", topics: ["Security Config", "JWT Authentication Filter", "Role-Based Access", "OAuth2 Resource Server", "CSRF & CORS"] },
            { title: "Testing & Microservices", topics: ["JUnit 5 & Mockito", "MockMvc", "Testcontainers", "Spring Cloud (Config, Gateway, Eureka)", "Docker & Kubernetes"] },
        ],
    },

    // ── 3 ── Programming Languages ─────────────────────────────────────────
    {
        title: "Go Developer",
        description: "Learn Go for building fast, concurrent, cloud-native systems.",
        category: "Programming",
        sections: [
            { title: "Go Fundamentals", topics: ["Variables & Types", "Functions", "Structs & Interfaces", "Pointers", "Packages & Modules", "Error Handling"] },
            { title: "Concurrency", topics: ["Goroutines", "Channels", "Select Statement", "sync.WaitGroup & Mutex", "Context Package", "Worker Pools"] },
            { title: "Standard Library", topics: ["fmt, strings, strconv", "io & os", "net/http", "encoding/json", "time", "testing"] },
            { title: "Web Development", topics: ["HTTP Server (net/http)", "Gin Framework", "Echo Framework", "Fiber Framework", "Middleware", "Routing"] },
            { title: "Database & Storage", topics: ["database/sql", "sqlx", "GORM ORM", "Redis (go-redis)", "PostgreSQL", "Migrations"] },
            { title: "Testing & Tools", topics: ["Unit Testing (testing)", "Table-Driven Tests", "Benchmarks", "go vet & golangci-lint", "pprof Profiling"] },
            { title: "DevOps & Cloud", topics: ["Docker Multi-stage Builds", "GitHub Actions", "gRPC", "Protocol Buffers", "Kubernetes Go Clients"] },
        ],
    },
    {
        title: "Rust Developer",
        description: "Master Rust for safe, high-performance systems programming.",
        category: "Programming",
        sections: [
            { title: "Ownership & Borrowing", topics: ["Ownership Model", "Borrowing & References", "Lifetimes", "The Borrow Checker", "Clone vs Copy"] },
            { title: "Types & Traits", topics: ["Structs & Enums", "Pattern Matching", "Traits & Generics", "Trait Objects (dyn)", "Closures", "Iterators"] },
            { title: "Error Handling", topics: ["Result & Option", "? Operator", "Custom Error Types", "thiserror & anyhow", "Panic vs Error"] },
            { title: "Concurrency", topics: ["Threads & Send/Sync", "Arc & Mutex", "Channels", "Async/Await", "Tokio Runtime", "Rayon (Data Parallelism)"] },
            { title: "Web Development", topics: ["Actix-Web", "Axum Framework", "Reqwest (HTTP Client)", "Serde (JSON)", "SQLx (Async DB)", "Tower Middleware"] },
            { title: "Systems Programming", topics: ["Unsafe Rust", "FFI (C Interop)", "Memory Layout", "Embedded Rust", "WebAssembly (WASM)"] },
            { title: "Tooling & Ecosystem", topics: ["Cargo & Crates.io", "cargo test", "cargo bench", "Clippy & Rustfmt", "cargo doc"] },
        ],
    },
    {
        title: "Java Developer",
        description: "Complete guide to Java development from fundamentals to enterprise.",
        category: "Programming",
        sections: [
            { title: "Java Fundamentals", topics: ["JVM & JDK", "Primitive Types", "OOP (Classes, Inheritance, Polymorphism)", "Interfaces & Abstract Classes", "Enums", "Generics"] },
            { title: "Collections & Streams", topics: ["List, Set, Map", "Iterator Pattern", "Java Streams API", "Optional", "Comparable & Comparator", "Collections Utility"] },
            { title: "Concurrency", topics: ["Threads & Runnable", "ExecutorService", "CompletableFuture", "synchronized & volatile", "Concurrent Collections", "Virtual Threads (Project Loom)"] },
            { title: "Modern Java Features", topics: ["Records", "Sealed Classes", "Pattern Matching (instanceof)", "Text Blocks", "Switch Expressions", "Modules (JPMS)"] },
            { title: "Build Tools & Testing", topics: ["Maven", "Gradle", "JUnit 5", "Mockito", "AssertJ", "Testcontainers"] },
            { title: "Spring Ecosystem", topics: ["Spring Boot", "Spring MVC", "Spring Data", "Spring Security", "Spring Batch", "Spring Cloud"] },
            { title: "JVM Internals", topics: ["JVM Architecture", "Garbage Collection", "JIT Compilation", "Heap & Stack", "GraalVM & Native Image"] },
        ],
    },
    {
        title: "C# Developer",
        description: "Master C# and .NET for modern cross-platform development.",
        category: "Programming",
        sections: [
            { title: "C# Fundamentals", topics: ["Types & Variables", "OOP in C#", "Interfaces & Abstract Classes", "Delegates & Events", "Generics", "Records & Structs"] },
            { title: "LINQ & Collections", topics: ["IEnumerable & IQueryable", "LINQ Query Syntax", "LINQ Method Syntax", "Lazy Evaluation", "Span & Memory"] },
            { title: "Async Programming", topics: ["async / await", "Task & Task<T>", "CancellationToken", "ValueTask", "Parallel Class", "Channels"] },
            { title: ".NET Ecosystem", topics: [".NET 8 Overview", "NuGet Package Manager", "dotnet CLI", "MSBuild", "Project Structure", "Configuration & Options"] },
            { title: "ASP.NET Core", topics: ["Minimal APIs", "Controllers & Routing", "Middleware Pipeline", "Model Validation", "Swagger / OpenAPI", "SignalR (Real-time)"] },
            { title: "Entity Framework Core", topics: ["DbContext & DbSet", "Migrations", "LINQ Queries", "Relationships", "Transactions", "Performance (AsNoTracking)"] },
            { title: "Testing & Deployment", topics: ["xUnit / NUnit", "Moq", "Integration Tests (WebApplicationFactory)", "Docker", "Azure App Service", "GitHub Actions"] },
        ],
    },
    {
        title: "TypeScript Mastery",
        description: "Deep dive into TypeScript's type system for expert-level proficiency.",
        category: "Programming",
        sections: [
            { title: "Type System Basics", topics: ["Primitive Types", "Type Inference", "Union & Intersection Types", "Literal Types", "Type Narrowing", "never & unknown"] },
            { title: "Interfaces & Types", topics: ["interface vs type", "Extending Types", "Index Signatures", "Readonly & Partial", "Required & Pick", "Omit & Exclude"] },
            { title: "Generics", topics: ["Generic Functions", "Generic Interfaces", "Generic Classes", "Constraints (extends)", "Conditional Types", "Infer Keyword"] },
            { title: "Advanced Types", topics: ["Mapped Types", "Template Literal Types", "Discriminated Unions", "Variance (Covariance, Contravariance)", "Branded Types"] },
            { title: "Modules & Declarations", topics: ["Module System", "Declaration Files (.d.ts)", "Triple-Slash Directives", "Ambient Declarations", "DefinitelyTyped"] },
            { title: "Tooling & Configuration", topics: ["tsconfig.json Deep Dive", "Strict Mode Flags", "Path Aliases", "Project References", "ts-node", "Bundlers (esbuild, Rollup)"] },
            { title: "TypeScript + React", topics: ["Component Props Typing", "Hooks Typing", "Event Types", "Ref Typing", "Context Typing", "Generic Components"] },
        ],
    },

    // ── 4 ── Mobile ────────────────────────────────────────────────────────
    {
        title: "React Native Developer",
        description: "Build cross-platform iOS and Android apps with React Native.",
        category: "Mobile",
        sections: [
            { title: "React Native Fundamentals", topics: ["Core Components (View, Text, Image)", "StyleSheet API", "Flexbox Layouts", "Platform-Specific Code", "Metro Bundler"] },
            { title: "Navigation", topics: ["React Navigation Setup", "Stack Navigator", "Tab Navigator", "Drawer Navigator", "Deep Linking"] },
            { title: "State Management", topics: ["useState & useReducer", "Context API", "Redux Toolkit", "Zustand", "Jotai", "MMKV Storage"] },
            { title: "Native APIs", topics: ["Camera & Gallery", "Location & Maps", "Push Notifications (FCM)", "Biometrics", "Bluetooth", "Sensors"] },
            { title: "Networking & Data", topics: ["Fetch & Axios", "React Query", "GraphQL", "SQLite (expo-sqlite)", "AsyncStorage", "Offline Support"] },
            { title: "Expo Ecosystem", topics: ["Expo Router", "expo-dev-client", "EAS Build & Submit", "Over-the-Air Updates", "Expo Go"] },
            { title: "Testing & Performance", topics: ["Jest + @testing-library/react-native", "Detox E2E", "Flipper Debugging", "Hermes Engine", "Bundle Optimization"] },
        ],
    },
    {
        title: "Flutter Developer",
        description: "Build beautiful natively compiled apps with Flutter and Dart.",
        category: "Mobile",
        sections: [
            { title: "Dart Fundamentals", topics: ["Variables & Types", "Null Safety", "Functions & Closures", "Classes & Mixins", "Async/Await & Futures", "Streams"] },
            { title: "Flutter Widgets", topics: ["StatelessWidget vs StatefulWidget", "BuildContext", "Scaffold & Material", "Container & Padding", "Column, Row & Stack", "ListView & GridView"] },
            { title: "State Management", topics: ["setState", "InheritedWidget", "Provider", "Riverpod", "BLoC Pattern", "GetX"] },
            { title: "Navigation", topics: ["Navigator 1.0", "Navigator 2.0 (Router API)", "GoRouter", "Deep Linking", "Named Routes"] },
            { title: "Networking & Storage", topics: ["http & dio", "JSON Parsing", "Hive (Local DB)", "SQLite (sqflite)", "Firebase Integration"] },
            { title: "Animations", topics: ["AnimationController", "Tween Animations", "Hero Animations", "Implicit Animations", "Custom Painters"] },
            { title: "Testing & Publishing", topics: ["Widget Tests", "Integration Tests", "Flutter DevTools", "Flavors (Environments)", "Play Store & App Store Submission"] },
        ],
    },

    // ── 5 ── AI & ML Specializations ───────────────────────────────────────
    {
        title: "MLOps Engineer",
        description: "Operationalize machine learning models at scale.",
        category: "AI & ML",
        sections: [
            { title: "ML Fundamentals Recap", topics: ["Model Training Pipeline", "Feature Engineering", "Model Evaluation Metrics", "Overfitting & Regularization", "Reproducibility"] },
            { title: "Experiment Tracking", topics: ["MLflow Tracking", "Experiment Logging", "Model Registry", "Weights & Biases", "DVC for Data Versioning"] },
            { title: "CI/CD for ML", topics: ["GitHub Actions for ML", "CML (Continuous ML)", "Model Validation Gates", "Automated Testing for Models", "Drift Detection"] },
            { title: "Model Serving", topics: ["REST APIs (FastAPI + Model)", "ONNX Format", "TorchServe", "Triton Inference Server", "Streaming Predictions"] },
            { title: "Kubernetes for ML", topics: ["Kubeflow", "Argo Workflows", "GPU Node Pools", "Persistent Volume Claims", "Helm Charts for ML"] },
            { title: "Monitoring", topics: ["Data Drift (Evidently)", "Model Performance Monitoring", "Prometheus + Grafana", "Alerting", "A/B Testing in Production"] },
            { title: "Cloud ML Platforms", topics: ["AWS SageMaker", "Google Vertex AI", "Azure ML", "Databricks", "Feature Stores"] },
        ],
    },
    {
        title: "LLM Engineer",
        description: "Build production LLM applications with RAG, fine-tuning, and agents.",
        category: "AI & ML",
        sections: [
            { title: "Transformer Architecture", topics: ["Self-Attention Mechanism", "Multi-Head Attention", "Positional Encoding", "Encoder-Decoder", "GPT vs BERT", "Tokenization (BPE, WordPiece)"] },
            { title: "Prompt Engineering", topics: ["Zero-Shot & Few-Shot", "Chain-of-Thought (CoT)", "ReAct Framework", "System Prompts", "Prompt Templates", "Prompt Injection Defense"] },
            { title: "RAG (Retrieval-Augmented Generation)", topics: ["Document Chunking", "Embedding Models", "Vector Search", "Hybrid Search (BM25 + Dense)", "Reranking", "Contextual Compression"] },
            { title: "Vector Databases", topics: ["Pinecone", "Weaviate", "Qdrant", "pgvector (PostgreSQL)", "Chroma", "FAISS"] },
            { title: "Frameworks", topics: ["LangChain", "LlamaIndex", "Haystack", "DSPy", "Instructor", "Semantic Kernel"] },
            { title: "Fine-Tuning", topics: ["When to Fine-tune", "LoRA & QLoRA", "PEFT Library", "Dataset Preparation", "Hugging Face Trainer", "Evaluation (ROUGE, BLEU)"] },
            { title: "Agents & Production", topics: ["ReAct Agents", "Tool Use & Function Calling", "Multi-Agent Orchestration", "LLM Observability (LangSmith)", "Cost Optimization", "Safety & Guardrails"] },
        ],
    },
    {
        title: "Computer Vision Engineer",
        description: "Build intelligent systems that understand and generate visual content.",
        category: "AI & ML",
        sections: [
            { title: "Image Processing Basics", topics: ["Pixels & Color Spaces (RGB, HSV)", "Filtering (Gaussian, Sobel)", "Morphological Operations", "Histograms", "OpenCV Fundamentals"] },
            { title: "Convolutional Neural Networks", topics: ["CNN Architecture", "Convolutions & Pooling", "Batch Normalization", "ResNet & VGG", "MobileNet (Efficient Models)", "Transfer Learning"] },
            { title: "Object Detection", topics: ["YOLO (v5, v8, v11)", "Faster R-CNN", "SSD", "Detection Metrics (mAP, IoU)", "Non-Maximum Suppression", "Custom Dataset Training"] },
            { title: "Segmentation & Tracking", topics: ["Semantic Segmentation (DeepLab)", "Instance Segmentation (Mask R-CNN)", "SAM (Segment Anything)", "Object Tracking (ByteTrack)", "Video Analysis"] },
            { title: "Generative Models", topics: ["GANs (DCGAN, StyleGAN)", "Diffusion Models", "Stable Diffusion", "ControlNet", "Image-to-Image", "Inpainting"] },
            { title: "Vision Transformers", topics: ["ViT Architecture", "CLIP (Contrastive Learning)", "DINO", "Grounding DINO", "Multimodal Models (LLaVA)"] },
            { title: "Deployment & Optimization", topics: ["ONNX Export", "TensorRT", "OpenVINO", "Edge Deployment", "Gradio Demo", "REST API for CV Models"] },
        ],
    },
    {
        title: "NLP Engineer",
        description: "Build systems that understand and generate human language.",
        category: "AI & ML",
        sections: [
            { title: "Text Processing", topics: ["Tokenization", "Stemming & Lemmatization", "Stop Words", "TF-IDF", "N-grams", "Regular Expressions for NLP"] },
            { title: "Word Representations", topics: ["Bag of Words", "Word2Vec", "GloVe", "FastText", "Contextual Embeddings", "Sentence Transformers"] },
            { title: "Classical NLP", topics: ["Named Entity Recognition (NER)", "POS Tagging", "Dependency Parsing", "Coreference Resolution", "spaCy Library"] },
            { title: "Seq2Seq & Attention", topics: ["RNN & LSTM Recap", "Encoder-Decoder", "Bahdanau Attention", "Transformer Building Blocks", "BLEU Score"] },
            { title: "Pre-trained Models", topics: ["BERT & Variants (RoBERTa, DistilBERT)", "GPT Family", "T5 & FLAN-T5", "Llama 2/3", "Hugging Face Model Hub"] },
            { title: "Fine-tuning & Evaluation", topics: ["Text Classification Fine-tune", "QA Fine-tune", "Summarization", "Translation", "Benchmarks (GLUE, SuperGLUE)"] },
            { title: "Production NLP", topics: ["Model Quantization", "TorchScript", "ONNX Runtime", "Triton Server", "Semantic Search", "LLM APIs (OpenAI, Anthropic)"] },
        ],
    },

    // ── 6 ── Cloud Platforms ───────────────────────────────────────────────
    {
        title: "AWS Cloud Engineer",
        description: "Master Amazon Web Services for building and operating cloud systems.",
        category: "Cloud",
        sections: [
            { title: "AWS Fundamentals", topics: ["Global Infrastructure (Regions, AZs)", "IAM (Users, Roles, Policies)", "Billing & Cost Management", "CLI & SDK Setup", "Well-Architected Framework"] },
            { title: "Compute", topics: ["EC2 (Instances, AMIs, Security Groups)", "Lambda (Serverless)", "ECS (Fargate)", "Elastic Beanstalk", "Auto Scaling Groups"] },
            { title: "Storage", topics: ["S3 (Buckets, Policies, Versioning)", "EBS & EFS", "S3 Glacier", "Storage Gateway", "CloudFront CDN"] },
            { title: "Databases", topics: ["RDS (PostgreSQL, MySQL)", "Aurora Serverless", "DynamoDB", "ElastiCache (Redis)", "Redshift"] },
            { title: "Networking", topics: ["VPC (Subnets, Route Tables, NAT)", "Route 53 (DNS)", "API Gateway", "ALB & NLB", "Direct Connect & VPN"] },
            { title: "Security & Monitoring", topics: ["AWS KMS (Encryption)", "WAF & Shield", "CloudTrail & Config", "CloudWatch (Metrics, Logs, Alarms)", "Security Hub"] },
            { title: "Containers & Serverless", topics: ["EKS (Kubernetes)", "ECR (Container Registry)", "SAM & CDK", "Step Functions", "SQS & SNS", "EventBridge"] },
        ],
    },
    {
        title: "Google Cloud Engineer",
        description: "Build and scale applications on Google Cloud Platform.",
        category: "Cloud",
        sections: [
            { title: "GCP Fundamentals", topics: ["GCP Architecture", "Projects & Organizations", "IAM (Roles, Service Accounts)", "gcloud CLI", "Pricing & Billing"] },
            { title: "Compute", topics: ["Compute Engine (VMs)", "Cloud Run (Containers)", "Cloud Functions", "App Engine", "GKE (Kubernetes)"] },
            { title: "Storage & Databases", topics: ["Cloud Storage (Buckets)", "Cloud SQL (PostgreSQL, MySQL)", "Firestore (NoSQL)", "Bigtable", "Spanner (Global SQL)"] },
            { title: "BigQuery & Analytics", topics: ["BigQuery Architecture", "SQL in BigQuery", "Partitioned & Clustered Tables", "Scheduled Queries", "Looker Studio"] },
            { title: "Networking", topics: ["VPC Networks", "Cloud Load Balancing", "Cloud DNS", "Cloud CDN", "Private Service Connect"] },
            { title: "AI & ML on GCP", topics: ["Vertex AI", "AutoML", "AI Platform Notebooks", "Gemini API", "Document AI", "Vision AI"] },
            { title: "DevOps & Security", topics: ["Cloud Build (CI/CD)", "Artifact Registry", "Secret Manager", "Cloud Armor", "Security Command Center", "Monitoring & Logging (Cloud Ops)"] },
        ],
    },
    {
        title: "Azure Cloud Engineer",
        description: "Design and deploy solutions on Microsoft Azure.",
        category: "Cloud",
        sections: [
            { title: "Azure Fundamentals", topics: ["Azure Architecture", "Subscriptions & Resource Groups", "Azure Active Directory (Entra ID)", "Azure Portal & CLI", "Cost Management"] },
            { title: "Compute & Containers", topics: ["Azure VMs", "Azure Functions (Serverless)", "Azure Container Apps", "AKS (Kubernetes)", "Azure App Service"] },
            { title: "Storage & Databases", topics: ["Blob Storage", "Azure SQL Database", "Cosmos DB (NoSQL)", "Azure Cache for Redis", "Azure Data Lake"] },
            { title: "Networking", topics: ["Virtual Networks (VNet)", "Azure Load Balancer", "Application Gateway", "Azure DNS", "ExpressRoute"] },
            { title: "Identity & Security", topics: ["Azure AD Roles & RBAC", "Managed Identities", "Key Vault (Secrets & Certs)", "Microsoft Defender", "Azure Policy"] },
            { title: "DevOps & Monitoring", topics: ["Azure DevOps (Pipelines, Repos)", "GitHub Actions + Azure", "Azure Monitor & Log Analytics", "Application Insights", "Bicep & Terraform"] },
        ],
    },

    // ── 7 ── Infrastructure & DevOps Specializations ───────────────────────
    {
        title: "Kubernetes Engineer",
        description: "Master Kubernetes for deploying and managing containerized workloads.",
        category: "Infrastructure",
        sections: [
            { title: "K8s Architecture", topics: ["Control Plane Components", "Worker Nodes", "etcd", "kube-apiserver", "kubelet & kube-proxy", "kubectl Setup"] },
            { title: "Workloads", topics: ["Pods", "Deployments", "StatefulSets", "DaemonSets", "Jobs & CronJobs", "ReplicaSets"] },
            { title: "Services & Networking", topics: ["ClusterIP, NodePort, LoadBalancer", "Ingress Controllers (Nginx, Traefik)", "NetworkPolicies", "CoreDNS", "Service Mesh (Istio)"] },
            { title: "Storage", topics: ["Volumes & PersistentVolumes", "StorageClasses", "PersistentVolumeClaims", "CSI Drivers", "StatefulSet Storage"] },
            { title: "Configuration & Secrets", topics: ["ConfigMaps", "Secrets Management", "Environment Variables", "Downward API", "External Secrets Operator"] },
            { title: "Security", topics: ["RBAC (Roles, RoleBindings)", "Pod Security Standards", "Network Policies", "OPA / Gatekeeper", "Image Scanning (Trivy)"] },
            { title: "Helm & GitOps", topics: ["Helm Charts", "Chart Templating", "ArgoCD", "Flux CD", "Kustomize", "Monitoring (Prometheus Stack)"] },
        ],
    },
    {
        title: "Site Reliability Engineer",
        description: "Apply software engineering principles to operations and reliability.",
        category: "Infrastructure",
        sections: [
            { title: "SRE Principles", topics: ["SRE vs DevOps", "Toil Reduction", "Error Budgets", "Blameless Postmortems", "SRE Team Structure"] },
            { title: "Service Level Objectives", topics: ["SLIs (Metrics that Matter)", "SLOs & SLAs", "Error Budget Policy", "Reliability Targets", "User Journey Mapping"] },
            { title: "Observability", topics: ["The Three Pillars (Metrics, Logs, Traces)", "Prometheus & Grafana", "Distributed Tracing (Jaeger, Tempo)", "Structured Logging", "OpenTelemetry"] },
            { title: "Incident Management", topics: ["On-call Practices", "Incident Severity Levels", "Runbooks & Playbooks", "Root Cause Analysis", "Post-incident Review"] },
            { title: "Capacity Planning", topics: ["Traffic Modeling", "Load Testing (k6, Locust)", "Auto-scaling Strategies", "Cost Optimization", "Performance Budgets"] },
            { title: "Automation & Chaos", topics: ["Automation Frameworks (Ansible, Terraform)", "Configuration Drift", "Chaos Engineering (Chaos Monkey)", "Game Days", "Graceful Degradation"] },
        ],
    },
    {
        title: "Linux Administration",
        description: "Master Linux for system administration and DevOps engineering.",
        category: "Infrastructure",
        sections: [
            { title: "Linux Fundamentals", topics: ["File System Hierarchy", "Basic Commands", "File Permissions (chmod, chown)", "Redirects & Pipes", "Text Processing (grep, sed, awk)", "Vim Basics"] },
            { title: "Shell Scripting", topics: ["Bash Variables & Control Flow", "Functions", "Script Arguments", "Cron Jobs", "Signal Handling", "Debugging (set -x)"] },
            { title: "User & Process Management", topics: ["User & Group Management", "sudo & PAM", "Process Management (ps, kill, nice)", "systemd Services", "Journaling (journalctl)"] },
            { title: "Networking", topics: ["IP Addressing & Subnetting", "iptables & nftables", "ss & netstat", "SSH Hardening", "DNS Configuration", "Network Troubleshooting"] },
            { title: "Storage & Filesystems", topics: ["LVM (Logical Volume Management)", "RAID Configurations", "Mount Points & fstab", "NFS & SMB", "Disk Quotas", "ZFS / Btrfs"] },
            { title: "Security", topics: ["SELinux & AppArmor", "Fail2ban", "OpenSSL Certificates", "Audit Framework", "Hardening Guides (CIS Benchmarks)", "Firewalld"] },
            { title: "Automation", topics: ["Ansible Playbooks", "Bash Automation Scripts", "Puppet & Chef Overview", "Cloud-init", "systemd Timers"] },
        ],
    },
    {
        title: "Docker & Containers",
        description: "Master containerization with Docker for development and production.",
        category: "Infrastructure",
        sections: [
            { title: "Container Fundamentals", topics: ["What are Containers?", "Containers vs VMs", "Namespaces & cgroups", "Container Runtimes (containerd, runc)", "OCI Standards"] },
            { title: "Docker CLI", topics: ["docker run & exec", "docker ps, logs, inspect", "Port Binding", "Volume Mounts", "Networking Modes", "docker system prune"] },
            { title: "Dockerfile", topics: ["FROM & Base Images", "RUN, COPY, ADD", "CMD vs ENTRYPOINT", "Multi-stage Builds", "Layer Caching", "Dockerfile Best Practices"] },
            { title: "Images & Registry", topics: ["docker build & tag", "Docker Hub", "Private Registry", "Image Scanning (Trivy)", "Slim Images (distroless)", "BuildKit"] },
            { title: "Docker Compose", topics: ["Compose File Syntax", "Services, Volumes, Networks", "Environment Variables", "Health Checks", "Profiles", "Override Files"] },
            { title: "Security", topics: ["Non-root Users", "Read-only Filesystems", "Secrets Management", "Content Trust", "Capabilities", "Seccomp Profiles"] },
        ],
    },
    {
        title: "Terraform & IaC",
        description: "Provision and manage cloud infrastructure with Terraform.",
        category: "Infrastructure",
        sections: [
            { title: "IaC Concepts", topics: ["Infrastructure as Code Benefits", "Declarative vs Imperative", "Idempotency", "Drift Detection", "IaC Tools Comparison"] },
            { title: "Terraform Basics", topics: ["HCL Syntax", "Providers", "Resources", "Data Sources", "terraform init/plan/apply/destroy", "State File"] },
            { title: "Variables & Outputs", topics: ["Input Variables", "Local Values", "Output Values", "Variable Validation", "Sensitive Variables", "tfvars Files"] },
            { title: "State Management", topics: ["Local vs Remote State", "S3 + DynamoDB Backend", "State Locking", "terraform import", "terraform state mv", "Workspaces"] },
            { title: "Modules", topics: ["Creating Modules", "Module Sources (Registry, Git)", "Module Versioning", "Root vs Child Modules", "Reusable Module Patterns"] },
            { title: "CI/CD & Best Practices", topics: ["GitHub Actions with Terraform", "Atlantis", "Checkov (Security Scanning)", "tflint", "Terraform Cloud", "atlantis.yaml"] },
        ],
    },

    // ── 8 ── Data Engineering ──────────────────────────────────────────────
    {
        title: "Data Engineer",
        description: "Build robust data pipelines and infrastructure for analytics.",
        category: "Data Engineering",
        sections: [
            { title: "Data Fundamentals", topics: ["OLTP vs OLAP", "Data Warehouse vs Data Lake", "Batch vs Streaming", "Star & Snowflake Schema", "Data Governance"] },
            { title: "SQL Mastery", topics: ["Advanced JOINs", "Window Functions", "CTEs & Recursive Queries", "Indexing Strategies", "Query Optimization", "EXPLAIN ANALYZE"] },
            { title: "Python for Data Engineering", topics: ["pandas & pyarrow", "Writing ETL Scripts", "Generators for Large Data", "Parallel Processing", "SQLAlchemy", "Logging & Monitoring"] },
            { title: "Apache Spark", topics: ["Spark Architecture", "RDDs vs DataFrames", "SparkSQL", "Structured Streaming", "PySpark", "Performance Tuning (Partitions, Caching)"] },
            { title: "Message Streaming", topics: ["Apache Kafka", "Kafka Producers & Consumers", "Consumer Groups", "Schema Registry (Avro)", "Kafka Streams", "Apache Flink"] },
            { title: "Data Warehousing", topics: ["Snowflake", "dbt (Data Build Tool)", "BigQuery", "Redshift", "Dimensional Modeling", "Data Vault 2.0"] },
            { title: "Orchestration", topics: ["Apache Airflow DAGs", "TaskFlow API", "Sensors & Operators", "Prefect", "Dagster", "Monitoring Pipelines"] },
        ],
    },
    {
        title: "SQL & Database Mastery",
        description: "Master SQL and relational database design for data-intensive applications.",
        category: "Data Engineering",
        sections: [
            { title: "SQL Fundamentals", topics: ["SELECT, FROM, WHERE", "ORDER BY & LIMIT", "INSERT, UPDATE, DELETE", "Data Types", "NULL Handling", "Aliases"] },
            { title: "Joins & Aggregations", topics: ["INNER JOIN", "LEFT / RIGHT / FULL OUTER JOIN", "CROSS JOIN", "GROUP BY & HAVING", "Aggregate Functions", "DISTINCT"] },
            { title: "Subqueries & CTEs", topics: ["Subqueries (Correlated, Uncorrelated)", "Common Table Expressions (WITH)", "Recursive CTEs", "EXISTS vs IN", "Derived Tables"] },
            { title: "Window Functions", topics: ["ROW_NUMBER & RANK", "LAG & LEAD", "PARTITION BY", "Running Totals", "Moving Averages", "NTILE"] },
            { title: "Performance & Indexes", topics: ["B-tree Indexes", "Composite Indexes", "Covering Indexes", "Partial Indexes", "EXPLAIN ANALYZE", "Vacuuming (PostgreSQL)"] },
            { title: "Transactions & Integrity", topics: ["ACID Properties", "Isolation Levels", "Deadlocks & Mitigation", "CHECK Constraints", "Foreign Keys", "Triggers"] },
            { title: "Database Design", topics: ["ER Diagrams", "Normalization (1NF, 2NF, 3NF)", "Denormalization for Performance", "PostgreSQL Advanced Features", "Partitioning"] },
        ],
    },
    {
        title: "Big Data Engineering",
        description: "Process and analyze petabyte-scale data with big data technologies.",
        category: "Data Engineering",
        sections: [
            { title: "Hadoop Ecosystem", topics: ["HDFS Architecture", "MapReduce", "YARN", "Hive", "HBase", "Sqoop & Flume"] },
            { title: "Apache Spark Advanced", topics: ["Broadcast Variables & Accumulators", "Catalyst Optimizer", "Tungsten Engine", "Delta Lake", "Iceberg Tables", "Spark Connect"] },
            { title: "Stream Processing", topics: ["Kafka Architecture Deep Dive", "Apache Flink", "Spark Structured Streaming", "Watermarks & Late Data", "Exactly-Once Semantics"] },
            { title: "Data Lakes & Lakehouses", topics: ["S3 / GCS / ADLS as Data Lake", "Delta Lake Format", "Apache Iceberg", "Apache Hudi", "Data Catalog (Glue, Unity)"] },
            { title: "Cloud Analytics", topics: ["Snowflake Architecture", "Databricks Platform", "dbt Transformations", "BigQuery ML", "Redshift Spectrum"] },
            { title: "Data Governance", topics: ["Data Lineage", "Data Catalog", "Data Quality (Great Expectations)", "GDPR Compliance", "Column-Level Encryption", "Role-Based Access"] },
        ],
    },

    // ── 9 ── Architecture ─────────────────────────────────────────────────
    {
        title: "Software Architect",
        description: "Design robust, scalable software systems with proven architectural patterns.",
        category: "Architecture",
        sections: [
            { title: "Architecture Fundamentals", topics: ["Architectural Drivers (Quality Attributes)", "Trade-offs Analysis", "Architecture Decision Records (ADR)", "Documentation (C4 Model)", "Conway's Law"] },
            { title: "Design Patterns", topics: ["Creational Patterns (Factory, Builder, Singleton)", "Structural Patterns (Adapter, Decorator, Facade)", "Behavioral Patterns (Observer, Strategy, Command)", "CQRS & Event Sourcing"] },
            { title: "SOLID Principles", topics: ["Single Responsibility", "Open/Closed Principle", "Liskov Substitution", "Interface Segregation", "Dependency Inversion"] },
            { title: "API Design", topics: ["RESTful API Design Principles", "API Versioning", "gRPC & Protocol Buffers", "GraphQL Schema Design", "API Security", "Contract-First Design"] },
            { title: "Distributed Systems", topics: ["CAP Theorem", "Eventual Consistency", "Saga Pattern", "Two-Phase Commit", "Distributed Transactions", "Idempotency"] },
            { title: "Security Architecture", topics: ["Zero Trust Architecture", "Defense in Depth", "Threat Modeling (STRIDE)", "OAuth2 & OIDC Flows", "Secret Management", "Data Encryption Strategies"] },
        ],
    },
    {
        title: "Microservices Architecture",
        description: "Design, build, and operate microservices-based distributed systems.",
        category: "Architecture",
        sections: [
            { title: "Monolith to Microservices", topics: ["Monolithic Limitations", "Strangler Fig Pattern", "Service Decomposition", "Domain-Driven Design (Bounded Contexts)", "Team Topologies"] },
            { title: "Service Communication", topics: ["Synchronous (REST, gRPC)", "Asynchronous (Event-Driven)", "Message Brokers (Kafka, RabbitMQ)", "Choreography vs Orchestration", "API Gateway Pattern"] },
            { title: "Data Management", topics: ["Database per Service", "Shared Data Anti-patterns", "Event Sourcing", "CQRS Pattern", "Saga Pattern (Transactions)", "Outbox Pattern"] },
            { title: "Resilience Patterns", topics: ["Circuit Breaker", "Retry with Exponential Backoff", "Timeout & Bulkhead", "Rate Limiting", "Health Checks", "Graceful Degradation"] },
            { title: "Observability", topics: ["Distributed Tracing (OpenTelemetry)", "Centralized Logging (ELK)", "Metrics (Prometheus)", "Service Mesh (Istio/Linkerd)", "Correlation IDs"] },
            { title: "Testing Strategies", topics: ["Unit Tests per Service", "Contract Testing (Pact)", "Consumer-Driven Contracts", "Integration Tests", "Chaos Engineering"] },
        ],
    },

    // ── 10 ── Game Development ─────────────────────────────────────────────
    {
        title: "Unity Game Developer",
        description: "Build 2D and 3D games with Unity and C#.",
        category: "Game Development",
        sections: [
            { title: "Unity Fundamentals", topics: ["Unity Editor Overview", "GameObjects & Hierarchy", "Transform Component", "Scenes & Assets", "Prefabs", "The Inspector"] },
            { title: "C# for Unity", topics: ["MonoBehaviour Lifecycle (Awake, Start, Update)", "Coroutines", "Events & Delegates", "ScriptableObjects", "Editor Scripting Basics"] },
            { title: "Physics & Collisions", topics: ["Rigidbody 2D & 3D", "Colliders", "Triggers vs Collisions", "Physics Layers", "Raycasting", "Character Controller"] },
            { title: "UI System", topics: ["Canvas & Anchors", "Text Mesh Pro", "Buttons & Events", "Sliders & Health Bars", "UI Animations", "UI Toolkit (New)"] },
            { title: "Audio & Graphics", topics: ["AudioSource & AudioMixer", "Particle Systems", "Shader Graph", "Lighting (Realtime & Baked)", "Post-Processing Stack", "Sprite Atlases"] },
            { title: "Game Architecture", topics: ["Game Manager Pattern", "Object Pooling", "State Machine (Animator)", "Observer Pattern (Events)", "Service Locator"] },
            { title: "Performance & Publishing", topics: ["Profiler Usage", "Draw Call Optimization", "LOD Groups", "Addressables", "Build Settings", "Platform Publishing"] },
        ],
    },
    {
        title: "Game Development Fundamentals",
        description: "Learn the math, algorithms, and patterns behind great games.",
        category: "Game Development",
        sections: [
            { title: "Game Math", topics: ["Vectors & Dot Product", "Cross Product", "Matrices & Transformations", "Quaternions for Rotation", "Interpolation (Lerp, Slerp)", "Trigonometry for Games"] },
            { title: "Game Loop & Architecture", topics: ["Fixed vs Variable Time Step", "Entity-Component-System (ECS)", "Scene Management", "Game States (State Machine)", "Event Systems"] },
            { title: "Input & Controls", topics: ["Input Mapping", "Gamepad Support", "Touch & Gesture", "Mouse Picking (Raycasting)", "Input Buffering"] },
            { title: "Physics Simulation", topics: ["Collision Detection (AABB, SAT)", "Physics Integration (Euler, Verlet)", "Rigid Body Dynamics", "Constraint Solving", "Spatial Partitioning (QuadTree)"] },
            { title: "Rendering Basics", topics: ["Rendering Pipeline Overview", "Sprites & Tilemaps", "Shader Basics (GLSL/HLSL)", "Sprite Batching", "Lighting Models (Phong)"] },
            { title: "AI & Game Design", topics: ["Finite State Machines", "Pathfinding (A*)", "Behavior Trees", "Game Balancing", "Procedural Generation", "Level Design Principles"] },
        ],
    },

    // ── 11 ── Quality & Career ─────────────────────────────────────────────
    {
        title: "QA & Test Engineering",
        description: "Master software quality assurance and test automation.",
        category: "Quality",
        sections: [
            { title: "Testing Fundamentals", topics: ["Testing Pyramid", "Test Types (Unit, Integration, E2E)", "Black-box vs White-box", "Test Planning & Strategy", "Bug Lifecycle", "Test Coverage"] },
            { title: "Unit Testing", topics: ["Jest / Vitest", "PyTest", "JUnit 5", "Arrange-Act-Assert Pattern", "Mocking & Stubbing", "Test Doubles"] },
            { title: "Integration Testing", topics: ["API Testing (Supertest, REST Assured)", "Database Testing (Testcontainers)", "Contract Testing (Pact)", "Test Data Management"] },
            { title: "E2E & UI Testing", topics: ["Playwright", "Cypress", "Selenium", "Page Object Model", "Visual Regression Testing", "Accessibility Testing (axe)"] },
            { title: "Performance Testing", topics: ["Load Testing (k6, JMeter)", "Stress Testing", "Spike Testing", "Response Time Analysis", "Bottleneck Identification"] },
            { title: "CI/CD for QA", topics: ["Test Pipeline Design", "Parallelizing Tests", "Flaky Test Management", "Test Reporting", "Quality Gates", "Shift-Left Testing"] },
        ],
    },
    {
        title: "Technical Interview Prep",
        description: "Systematic preparation for software engineering technical interviews.",
        category: "Career",
        sections: [
            { title: "Arrays & Strings", topics: ["Two Pointers", "Sliding Window", "Prefix Sums", "String Manipulation", "Sorting Algorithms", "Binary Search"] },
            { title: "Linked Lists & Stacks", topics: ["Linked List Operations", "Reverse a Linked List", "Detect Cycles (Floyd's)", "Stack & Queue Implementations", "Monotonic Stack", "Deque"] },
            { title: "Trees & Graphs", topics: ["Tree Traversals (DFS, BFS)", "Binary Search Trees", "Balanced Trees (AVL, Red-Black)", "Trie Data Structure", "Graph Representations", "Topological Sort"] },
            { title: "Dynamic Programming", topics: ["Memoization vs Tabulation", "Fibonacci & Coin Change", "Longest Common Subsequence", "Knapsack Problem", "DP on Grids", "State Machine DP"] },
            { title: "System Design", topics: ["Design Interview Framework", "URL Shortener Design", "Rate Limiter Design", "Distributed Cache Design", "Newsfeed Design", "WhatsApp Design"] },
            { title: "Soft Skills & Behavioral", topics: ["STAR Method", "Amazon Leadership Principles", "Problem-Solving Communication", "Salary Negotiation", "Offer Evaluation", "Mock Interview Practice"] },
        ],
    },
    {
        title: "UI/UX Engineering",
        description: "Bridge the gap between design and engineering for exceptional user experiences.",
        category: "Design",
        sections: [
            { title: "Design Fundamentals", topics: ["Visual Hierarchy", "Gestalt Principles", "Grid Systems", "Spacing & Layout", "Design Systems", "Atomic Design"] },
            { title: "Figma & Design Tools", topics: ["Figma Basics", "Components & Variants", "Auto Layout", "Prototyping", "Design Tokens", "Handoff to Dev (Inspect)"] },
            { title: "Accessibility (a11y)", topics: ["WCAG 2.1 Guidelines", "ARIA Attributes", "Keyboard Navigation", "Screen Reader Testing", "Color Contrast", "Focus Management"] },
            { title: "Color & Typography", topics: ["Color Theory", "HSL Color Model", "Semantic Color Tokens", "Type Scale (rem)", "Font Pairing", "Reading Legibility"] },
            { title: "Component Libraries", topics: ["Building Design Systems", "Storybook", "Radix UI / shadcn", "React Aria", "Tailwind CSS Patterns", "CSS Custom Properties"] },
            { title: "Animation & Motion", topics: ["Principles of Motion", "CSS Transitions & Keyframes", "Framer Motion", "Micro-interactions", "Skeleton Loading", "Page Transitions"] },
            { title: "User Research", topics: ["User Interviews", "Usability Testing", "Heuristic Evaluation", "A/B Testing", "Analytics (GA4, Mixpanel)", "Jobs to Be Done Framework"] },
        ],
    },
    {
        title: "Open Source Contributing",
        description: "Become an effective open source contributor and maintainer.",
        category: "Career",
        sections: [
            { title: "Git Advanced", topics: ["Interactive Rebase", "Cherry-Pick", "git bisect", "Stash & Worktrees", "Reflog Recovery", "Submodules"] },
            { title: "GitHub Workflow", topics: ["Forking Workflow", "Feature Branches", "Pull Request Best Practices", "Draft PRs", "GitHub Actions (CI)", "GitHub CLI"] },
            { title: "Reading Codebases", topics: ["Navigating Large Repos", "Understanding Architecture from Tests", "Call Graph Tracing", "git log & blame", "Changelog Analysis"] },
            { title: "Documentation", topics: ["README Best Practices", "API Docs (JSDoc, Sphinx)", "Changelog (Keep a Changelog)", "Contributing Guide", "GitHub Wiki"] },
            { title: "Code Reviews", topics: ["Giving Constructive Feedback", "Reviewing Security Implications", "Performance Review Checklist", "Testing Review", "Merging Strategies"] },
            { title: "Building Your Own OSS", topics: ["Choosing a License (MIT, Apache, GPL)", "Semantic Versioning", "npm / PyPI Publishing", "GitHub Releases", "Community Building", "Sponsorship (Open Collective)"] },
        ],
    },

    // ── 12 ── Security Specialization ─────────────────────────────────────
    {
        title: "API Security & Design",
        description: "Design secure, well-structured APIs following modern best practices.",
        category: "Security",
        sections: [
            { title: "REST API Design Principles", topics: ["Resource Naming", "HTTP Methods & Status Codes", "Pagination (Cursor, Offset)", "HATEOAS", "Idempotency Keys", "Versioning Strategies"] },
            { title: "Authentication", topics: ["OAuth 2.0 Flows (Authorization Code, Client Credentials)", "OpenID Connect", "JWT Structure & Signing", "Refresh Tokens", "API Keys", "mTLS"] },
            { title: "Authorization Patterns", topics: ["RBAC (Role-Based Access)", "ABAC (Attribute-Based Access)", "Policy Engines (OPA)", "Scopes & Claims", "Resource Ownership Checks"] },
            { title: "Input Validation & Security", topics: ["Input Validation (Schema, Constraints)", "SQL Injection Prevention", "NoSQL Injection", "Command Injection", "Path Traversal", "Mass Assignment"] },
            { title: "Rate Limiting & Throttling", topics: ["Token Bucket Algorithm", "Sliding Window Counter", "Distributed Rate Limiting (Redis)", "Retry-After Headers", "DDoS Mitigation"] },
            { title: "Transport & Testing", topics: ["HTTPS & TLS Best Practices", "Certificate Pinning", "CORS Configuration", "Security Headers (HSTS, CSP)", "OWASP API Security Top 10", "Penetration Testing APIs"] },
        ],
    },
];
